version: '2'
services:
  web:
    image: node:alpine
    ports:
    - 4200:4200
    - 4201:4201
    restart: never
    working_dir: /usr/src/app
    volumes:
    - .:/usr/src/app
    command: sh -c 'npm install; npm rebuild node-sass; npm run start:gourmands &! npm run start:festy;'
