version: '2'
services:
  load-balancer-festy:
    ports:
    - ${FESTY_HOST_PORT_WEB}
    image: rancher/lb-service-haproxy:v0.5.9
    labels:
      proxy_url: ${FESTY_EXPOSE_URL}
  web-festy:
    image: krack/festyrepasduloup:${TAG}
    restart: always
    labels:
      io.rancher.container.pull_image: always
  load-balancer-gourmands:
    ports:
    - ${GOURMANDS_HOST_PORT_WEB}
    image: rancher/lb-service-haproxy:v0.5.9
    labels:
      proxy_url: ${GOURMANDS_EXPOSE_URL}
  web-gourmands:
    image: krack/lesloupsgourmands:${TAG}
    restart: always
    labels:
      io.rancher.container.pull_image: always
