version: '2'
services:
  load-balancer:
    ports:
    - ${HOST_PORT_WEB}
    image: rancher/lb-service-haproxy:v0.5.9
    labels:
      proxy_url: ${EXPOSE_URL}
  web:
    image: krack/aps-shared-web:${TAG}
    restart: always
    labels:
      io.rancher.container.pull_image: always
